"""Kid-safe bedtime story generator orchestrator.

This module wires together a Self-Refine pipeline (arXiv:2303.17651) on a single
LLM (gpt-3.5-turbo). A parent's free-form request is first routed by a
categorizer into one of four story buckets (ADVENTURE, FRIENDSHIP, CURIOSITY,
CALMING). A persona-bearing storyteller then drafts a 4-beat bedtime tale,
which is scored by a persona-free G-Eval style judge against a kid-safety
constitution and a five-criterion rubric. Deterministic readability metrics
(Flesch-Kincaid grade, hard-vocab %, sentence length) are passed in as
objective evidence so the LLM does not hallucinate its own readability. If the
judge's overall score falls below the pass threshold, a Kid Reaction Simulator
proxy-audience supplies child-flavored feedback, and the refiner makes
surgical edits targeted at the single weakest dimension. The loop runs at most
MAX_REFINE_ITERS times and prints per-iteration progress.

What I'd build next
-------------------
With 2 more hours I'd add (a) a tiny SQLite-backed memory of past stories per
child so a returning request like "another story about Pip" continues the
same world, (b) replace the deterministic readability gate with a calibrated
regression head trained on a small set of teacher-rated stories, and (c) add
an audio output via TTS with paragraph-level pause hints generated by the
storyteller — turning bedtime mode into a true wind-down experience.
"""

import os
import json
import re
import sys
import time
from typing import Optional

from dotenv import load_dotenv
import openai

from prompts import (
    MODEL,
    CATEGORIES,
    CATEGORIZER_PROMPT,
    STORYTELLER_PERSONAS,
    JSON_FIX_PROMPT,
    build_storyteller_prompt,
    build_judge_prompt,
    build_refiner_prompt,
    build_kid_reaction_prompt,
)
from readability import compute_metrics, format_metrics_for_judge

load_dotenv()
openai.api_key = os.getenv("OPENAI_API_KEY")
MAX_REFINE_ITERS = int(os.getenv("STORY_MAX_REFINE_ITERS", "2"))
MIN_PASS_SCORE = float(os.getenv("STORY_MIN_PASS_SCORE", "4.0"))

if openai.api_key is None or openai.api_key.startswith("sk-REPLACE_ME"):
    print(
        "ERROR: OPENAI_API_KEY is not set. Please add a real key to your .env "
        "file (see .env.example) and try again."
    )
    sys.exit(1)


def call_model(
    messages: list[dict], temperature: float = 0.7, max_tokens: int = 800
) -> str:
    """Wrap openai.ChatCompletion.create with a single retry on transient errors."""
    try:
        resp = openai.ChatCompletion.create(
            model=MODEL,
            messages=messages,
            temperature=temperature,
            max_tokens=max_tokens,
        )
    except (openai.error.RateLimitError, openai.error.APIError, openai.error.Timeout):
        time.sleep(2)
        resp = openai.ChatCompletion.create(
            model=MODEL,
            messages=messages,
            temperature=temperature,
            max_tokens=max_tokens,
        )
    return resp.choices[0].message["content"].strip()


def categorize(request: str) -> str:
    """Route a parent's request into one of CATEGORIES; default FRIENDSHIP on garbage."""
    prompt = CATEGORIZER_PROMPT.format(request=request)
    raw = call_model(
        [{"role": "user", "content": prompt}], temperature=0.0, max_tokens=10
    )
    label = raw.strip().upper()
    # Strip any stray punctuation/quotes the model may include.
    label = re.sub(r"[^A-Z]", "", label)
    if label not in CATEGORIES:
        print(f"WARN: categorizer returned '{raw}'; defaulting to FRIENDSHIP.")
        return "FRIENDSHIP"
    return label


def generate_story(category: str, request: str) -> str:
    """Draft a story with the persona-bearing storyteller (temp=0.8)."""
    messages = build_storyteller_prompt(category, request)
    return call_model(messages, temperature=0.8, max_tokens=900)


def _extract_json_blob(text: str) -> Optional[str]:
    """Strip ```json fences and grab the outermost {...} blob."""
    cleaned = re.sub(r"```(?:json)?", "", text).replace("```", "")
    match = re.search(r"\{[\s\S]*\}", cleaned)
    return match.group(0) if match else None


def _validate_judge_dict(parsed: dict) -> dict:
    """Ensure expected keys exist; backfill `overall` from scores mean if missing."""
    required = {"scores", "weakest", "critique"}
    missing = required - parsed.keys()
    if missing:
        raise ValueError(f"judge JSON missing keys: {missing}")
    if "overall" not in parsed or parsed.get("overall") is None:
        scores = parsed["scores"]
        parsed["overall"] = round(sum(scores.values()) / len(scores), 2)
    return parsed


def judge_story(story: str, metrics: dict) -> dict:
    """G-Eval judge with one JSON-fix retry; returns validated dict."""
    messages = build_judge_prompt(story, metrics)
    raw = call_model(messages, temperature=0.2, max_tokens=600)

    blob = _extract_json_blob(raw)
    if blob is not None:
        try:
            return _validate_judge_dict(json.loads(blob))
        except (json.JSONDecodeError, ValueError):
            pass

    # One retry: send the malformed output back with the JSON_FIX_PROMPT.
    fix_messages = [
        {"role": "user", "content": f"Previous output:\n{raw}\n\n{JSON_FIX_PROMPT}"}
    ]
    raw2 = call_model(fix_messages, temperature=0.0, max_tokens=400)
    blob2 = _extract_json_blob(raw2)
    if blob2 is None:
        raise ValueError(f"judge produced unparseable output twice: {raw2!r}")
    return _validate_judge_dict(json.loads(blob2))


def refine_story(
    category: str,
    prev_story: str,
    judge_result: dict,
    kid_reactions: Optional[str],
) -> str:
    """Surgical refinement aimed at judge_result['weakest']."""
    messages = build_refiner_prompt(
        category=category,
        prev_story=prev_story,
        judge_critique=judge_result["critique"],
        weakest=judge_result["weakest"],
        kid_reactions=kid_reactions,
    )
    return call_model(messages, temperature=0.7, max_tokens=900)


def get_kid_reactions(story: str) -> str:
    """Kid Reaction Simulator — 3 short reactions, one per line."""
    messages = build_kid_reaction_prompt(story)
    return call_model(messages, temperature=0.9, max_tokens=200)


def run_pipeline(request: str) -> dict:
    """Main orchestration loop: categorize → generate → (judge → refine)*."""
    print("[1/?] Categorizing request...")
    category = categorize(request)

    persona_blurb = STORYTELLER_PERSONAS[category].split(".")[0]
    print(f"[2/?] Generating story (category={category}, persona={persona_blurb})...")
    story = generate_story(category, request)

    history: list[tuple[int, float, str]] = []
    judge_result: dict = {}
    kid_reactions: Optional[str] = None
    iterations = 0
    max_iters = MAX_REFINE_ITERS + 1

    for i in range(max_iters):
        iterations = i
        metrics = compute_metrics(story)
        # The judge's prompt already renders metrics; we pass the dict in.
        # format_metrics_for_judge is available for callers who want a one-liner.
        _ = format_metrics_for_judge(metrics)
        print(f"[3/?] Judging story (iter {i})...")
        judge_result = judge_story(story, metrics)

        overall = float(judge_result["overall"])
        weakest = judge_result["weakest"]
        history.append((i, overall, weakest))

        is_last = i == max_iters - 1
        if overall >= MIN_PASS_SCORE:
            print(f"Iter {i}: overall={overall} (weakest={weakest}) — PASS")
            break
        if is_last:
            print(f"Iter {i}: overall={overall} (weakest={weakest}) — max iters reached")
            break

        print(f"Iter {i}: overall={overall} (weakest={weakest}) — refining...")
        # Kid reactions only after the FIRST iteration's judge, to inform refinement.
        if i == 0:
            print(f"[4/?] Gathering kid reactions...")
            kid_reactions = get_kid_reactions(story)
        print(f"[5/?] Refining story (iter {i + 1})...")
        story = refine_story(category, story, judge_result, kid_reactions)

    return {
        "category": category,
        "story": story,
        "iterations": iterations,
        "final_judge": judge_result,
        "history": history,
    }


def main() -> None:
    request = input("What kind of story do you want to hear? ")
    result = run_pipeline(request)

    final_judge = result["final_judge"]
    overall = final_judge.get("overall", 0.0)
    scores = final_judge.get("scores", {})

    bar = "=" * 60
    print()
    print(bar)
    print(
        f"Final story (category: {result['category']}, "
        f"iterations: {result['iterations']}, score: {overall})"
    )
    print(bar)
    print(result["story"])
    print(bar)
    score_line = " ".join(f"{k}={v}" for k, v in scores.items())
    print(f"Scores: {score_line}")

    user_change = input(
        "\nWant any changes? (e.g., 'sillier', 'shorter', 'more dragons') "
        "— press ENTER to skip: "
    ).strip()
    if user_change:
        fake_judge = {
            "weakest": "user_request",
            "critique": user_change,
            "scores": scores,
            "overall": overall,
        }
        revised = refine_story(
            result["category"], result["story"], fake_judge, kid_reactions=None
        )
        print()
        print(bar)
        print(f"Revised story (per your request: {user_change!r})")
        print(bar)
        print(revised)
        print(bar)


if __name__ == "__main__":
    main()
