"""Kid-safe bedtime story generator orchestrator.

This module wires together a Self-Refine pipeline (arXiv:2303.17651) on a single
LLM (gpt-3.5-turbo). A parent's free-form request is first routed by a
categorizer into one of four story buckets (ADVENTURE, FRIENDSHIP, CURIOSITY,
CALMING). A persona-bearing storyteller then drafts a 4-beat bedtime tale,
which is scored by a persona-free G-Eval style judge against a kid-safety
constitution and a five-criterion rubric. Deterministic readability metrics
(Flesch-Kincaid grade, hard-vocab %, sentence length) are passed in as
objective evidence so the LLM does not hallucinate its own readability. If the
judge's overall score falls below the pass threshold, a Kid Reaction Simulator
proxy-audience supplies child-flavored feedback, and the refiner makes
surgical edits targeted at the single weakest dimension. The loop runs at most
MAX_REFINE_ITERS times and prints per-iteration progress.

What I'd build next
-------------------
With 2 more hours I'd add (a) a tiny SQLite-backed memory of past stories per
child so a returning request like "another story about Pip" continues the
same world, (b) replace the deterministic readability gate with a calibrated
regression head trained on a small set of teacher-rated stories, and (c) add
an audio output via TTS with paragraph-level pause hints generated by the
storyteller — turning bedtime mode into a true wind-down experience.
"""

import argparse
import contextvars
import os
import json
import re
import sys
import time
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv
import openai

from prompts import (
    MODEL,
    CATEGORIES,
    CATEGORIZER_PROMPT,
    STORYTELLER_PERSONAS,
    JSON_FIX_PROMPT,
    build_storyteller_prompt,
    build_judge_prompt,
    build_refiner_prompt,
    build_kid_reaction_prompt,
)
from readability import compute_metrics, format_metrics_for_judge
from specialists import (
    USER_REQUEST_SENTINEL,
    build_specialist_prompt,
    dispatch,
)
import trace as trace_mod

load_dotenv()
openai.api_key = os.getenv("OPENAI_API_KEY")
MAX_REFINE_ITERS = int(os.getenv("STORY_MAX_REFINE_ITERS", "2"))
MIN_PASS_SCORE = float(os.getenv("STORY_MIN_PASS_SCORE", "4.0"))

# Holds the current pipeline run_id so call_model can attribute calls without
# every caller having to thread the id through. Set by run_pipeline.
_current_run_id: contextvars.ContextVar[Optional[str]] = contextvars.ContextVar(
    "_current_run_id", default=None
)

if openai.api_key is None or openai.api_key.startswith("sk-REPLACE_ME"):
    print(
        "ERROR: OPENAI_API_KEY is not set. Please add a real key to your .env "
        "file (see .env.example) and try again."
    )
    sys.exit(1)


def call_model(
    messages: list[dict],
    temperature: float = 0.7,
    max_tokens: int = 800,
    *,
    role: str = "unknown",
    iteration: int = -1,
) -> str:
    """Wrap openai.ChatCompletion.create with one retry on transient errors,
    and route through trace.record_call so per-call latency / tokens / cost
    land in SQLite (when STORY_DB_PATH is set)."""
    def _do_call():
        try:
            return openai.ChatCompletion.create(
                model=MODEL,
                messages=messages,
                temperature=temperature,
                max_tokens=max_tokens,
            )
        except (openai.error.RateLimitError, openai.error.APIError, openai.error.Timeout):
            time.sleep(2)
            return openai.ChatCompletion.create(
                model=MODEL,
                messages=messages,
                temperature=temperature,
                max_tokens=max_tokens,
            )

    return trace_mod.record_call(
        run_id=_current_run_id.get(),
        role=role,
        iteration=iteration,
        model=MODEL,
        temperature=temperature,
        fn=_do_call,
    )


def categorize(request: str) -> str:
    """Route a parent's request into one of CATEGORIES; default FRIENDSHIP on garbage."""
    prompt = CATEGORIZER_PROMPT.format(request=request)
    raw = call_model(
        [{"role": "user", "content": prompt}],
        temperature=0.0,
        max_tokens=10,
        role="categorizer",
        iteration=-1,
    )
    label = raw.strip().upper()
    # Strip any stray punctuation/quotes the model may include.
    label = re.sub(r"[^A-Z]", "", label)
    if label not in CATEGORIES:
        print(f"WARN: categorizer returned '{raw}'; defaulting to FRIENDSHIP.")
        return "FRIENDSHIP"
    return label


def generate_story(category: str, request: str) -> str:
    """Draft a story with the persona-bearing storyteller (temp=0.8)."""
    messages = build_storyteller_prompt(category, request)
    return call_model(
        messages, temperature=0.8, max_tokens=900,
        role="storyteller", iteration=-1,
    )


def _extract_json_blob(text: str) -> Optional[str]:
    """Strip ```json fences and grab the outermost {...} blob."""
    cleaned = re.sub(r"```(?:json)?", "", text).replace("```", "")
    match = re.search(r"\{[\s\S]*\}", cleaned)
    return match.group(0) if match else None


def _validate_judge_dict(parsed: dict) -> dict:
    """Ensure expected keys exist; backfill `overall` from scores mean if missing."""
    required = {"scores", "weakest", "critique"}
    missing = required - parsed.keys()
    if missing:
        raise ValueError(f"judge JSON missing keys: {missing}")
    if "overall" not in parsed or parsed.get("overall") is None:
        scores = parsed["scores"]
        parsed["overall"] = round(sum(scores.values()) / len(scores), 2)
    return parsed


def judge_story(story: str, metrics: dict, iteration: int = 0) -> dict:
    """G-Eval judge with one JSON-fix retry; returns validated dict."""
    messages = build_judge_prompt(story, metrics)
    raw = call_model(
        messages, temperature=0.2, max_tokens=600,
        role="judge", iteration=iteration,
    )

    blob = _extract_json_blob(raw)
    if blob is not None:
        try:
            return _validate_judge_dict(json.loads(blob))
        except (json.JSONDecodeError, ValueError):
            pass

    # One retry: send the malformed output back with the JSON_FIX_PROMPT.
    fix_messages = [
        {"role": "user", "content": f"Previous output:\n{raw}\n\n{JSON_FIX_PROMPT}"}
    ]
    raw2 = call_model(
        fix_messages, temperature=0.0, max_tokens=400,
        role="json_fix", iteration=iteration,
    )
    blob2 = _extract_json_blob(raw2)
    if blob2 is None:
        raise ValueError(f"judge produced unparseable output twice: {raw2!r}")
    return _validate_judge_dict(json.loads(blob2))


def refine_story(
    category: str,
    prev_story: str,
    judge_result: dict,
    kid_reactions: Optional[str],
    iteration: int = 0,
    edit_log: Optional[list[tuple[int, str, str]]] = None,
) -> str:
    """Surgical refinement aimed at judge_result['weakest'].

    Tier 2 routing:
      - If `weakest` is one of the 5 rubric dimensions, dispatch to that
        dimension's specialist sub-agent (persona-free editor with focused
        instructions). Trace tag: `specialist:<dim>`.
      - If `weakest` is anything else (e.g. user free-text 'sillier please'
        with weakest='user_request'), fall back to the legacy generic
        refiner. Trace tag: `refiner:generic`.
    """
    weakest = judge_result["weakest"]
    specialist_key = dispatch(weakest)
    edit_log = edit_log or []

    if specialist_key == USER_REQUEST_SENTINEL:
        # Legacy generic refiner — handles user feedback that doesn't map
        # to any rubric dimension.
        messages = build_refiner_prompt(
            category=category,
            prev_story=prev_story,
            judge_critique=judge_result["critique"],
            weakest=weakest,
            kid_reactions=kid_reactions,
        )
        return call_model(
            messages, temperature=0.7, max_tokens=900,
            role="refiner:generic", iteration=iteration,
        )

    print(f"  [dispatch] weakest={weakest} -> specialist={specialist_key}")
    messages = build_specialist_prompt(
        weakest=specialist_key,
        category=category,
        prev_story=prev_story,
        judge_critique=judge_result["critique"],
        kid_reactions=kid_reactions,
        edit_log=edit_log,
    )
    return call_model(
        messages, temperature=0.6, max_tokens=900,
        role=f"specialist:{specialist_key}", iteration=iteration,
    )


def get_kid_reactions(story: str, iteration: int = 0) -> str:
    """Kid Reaction Simulator — 3 short reactions, one per line."""
    messages = build_kid_reaction_prompt(story)
    return call_model(
        messages, temperature=0.9, max_tokens=200,
        role="kid_reaction", iteration=iteration,
    )


def run_pipeline(request: str) -> dict:
    """Main orchestration loop: categorize → generate → (judge → refine)*.

    Wrapped with trace.start_run / finish_run so every call inside is
    automatically attributed to a single SQLite run row (when STORY_DB_PATH
    is set; otherwise the trace layer is a no-op)."""
    run_id = trace_mod.start_run(request)
    token = _current_run_id.set(run_id)
    category: Optional[str] = None
    iterations = 0
    judge_result: dict = {}

    try:
        print("[1/?] Categorizing request...")
        category = categorize(request)

        persona_blurb = STORYTELLER_PERSONAS[category].split(".")[0]
        print(f"[2/?] Generating story (category={category}, persona={persona_blurb})...")
        story = generate_story(category, request)

        history: list[tuple[int, float, str]] = []
        edit_log: list[tuple[int, str, str]] = []
        kid_reactions: Optional[str] = None
        max_iters = MAX_REFINE_ITERS + 1

        for i in range(max_iters):
            iterations = i
            metrics = compute_metrics(story)
            _ = format_metrics_for_judge(metrics)
            print(f"[3/?] Judging story (iter {i})...")
            judge_result = judge_story(story, metrics, iteration=i)
            trace_mod.record_judge(run_id, i, judge_result)

            overall = float(judge_result["overall"])
            weakest = judge_result["weakest"]
            history.append((i, overall, weakest))

            is_last = i == max_iters - 1
            if overall >= MIN_PASS_SCORE:
                print(f"Iter {i}: overall={overall} (weakest={weakest}) — PASS")
                break
            if is_last:
                print(f"Iter {i}: overall={overall} (weakest={weakest}) — max iters reached")
                break

            print(f"Iter {i}: overall={overall} (weakest={weakest}) — refining...")
            if i == 0:
                print(f"[4/?] Gathering kid reactions...")
                kid_reactions = get_kid_reactions(story, iteration=i)
            print(f"[5/?] Refining story (iter {i + 1})...")
            specialist_key = dispatch(weakest)
            edit_log.append((i + 1, specialist_key, weakest))
            story = refine_story(
                category, story, judge_result, kid_reactions,
                iteration=i + 1, edit_log=edit_log[:-1],
            )

        final_overall = float(judge_result.get("overall", 0.0))
        trace_mod.finish_run(
            run_id,
            category=category,
            iterations=iterations,
            final_overall=final_overall,
            passed=final_overall >= MIN_PASS_SCORE,
        )
        return {
            "category": category,
            "story": story,
            "iterations": iterations,
            "final_judge": judge_result,
            "history": history,
        }
    except Exception as e:
        trace_mod.finish_run(
            run_id,
            category=category,
            iterations=iterations,
            error=str(e)[:500],
        )
        raise
    finally:
        _current_run_id.reset(token)


def _maybe_synthesize(text: str, path: Path, voice: str) -> None:
    """Best-effort TTS — print path on success, warn on failure, never crash."""
    try:
        from tts_voice import TTSError, extract_story_block, synthesize
        out = synthesize(extract_story_block(text), path, voice=voice)
        print(f"\nAudio saved: {out}")
    except Exception as e:  # ImportError or TTSError
        print(f"\nTTS warning: {e}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Kid-safe bedtime story generator (gpt-3.5-turbo Self-Refine pipeline)."
    )
    parser.add_argument(
        "--voice",
        action="store_true",
        help="After generating, also synthesize the final story to MP3 via OpenAI TTS-1.",
    )
    parser.add_argument(
        "--voice-name",
        default="shimmer",
        help="TTS voice name (default: shimmer — soft/intimate, best for bedtime).",
    )
    parser.add_argument(
        "--audio-path",
        default="output.mp3",
        help="Where to save the MP3 (default: output.mp3 in cwd; gitignored).",
    )
    args = parser.parse_args()

    request = input("What kind of story do you want to hear? ")
    result = run_pipeline(request)

    final_judge = result["final_judge"]
    overall = final_judge.get("overall", 0.0)
    scores = final_judge.get("scores", {})

    bar = "=" * 60
    print()
    print(bar)
    print(
        f"Final story (category: {result['category']}, "
        f"iterations: {result['iterations']}, score: {overall})"
    )
    print(bar)
    print(result["story"])
    print(bar)
    score_line = " ".join(f"{k}={v}" for k, v in scores.items())
    print(f"Scores: {score_line}")

    final_text = result["story"]
    user_change = input(
        "\nWant any changes? (e.g., 'sillier', 'shorter', 'more dragons') "
        "— press ENTER to skip: "
    ).strip()
    if user_change:
        fake_judge = {
            "weakest": "user_request",
            "critique": user_change,
            "scores": scores,
            "overall": overall,
        }
        revised = refine_story(
            result["category"], result["story"], fake_judge, kid_reactions=None
        )
        print()
        print(bar)
        print(f"Revised story (per your request: {user_change!r})")
        print(bar)
        print(revised)
        print(bar)
        final_text = revised

    if args.voice:
        _maybe_synthesize(final_text, Path(args.audio_path), args.voice_name)


if __name__ == "__main__":
    main()
